### ISSUE TITLE
Invalid Syntax in engine.py - line 115, self.seed = 5L

### ISSUE THREAD

**Issue by ghost** [jadianes/spark-movie-lens#19]
(C:\Program Files\Anaconda3) F:\Data Science\movielens\spark-movie-lens>server.py
Traceback (most recent call last):
  File "F:\Data Science\movielens\spark-movie-lens\server.py", line 3, in <module>
    from app import create_app
  File "F:\Data Science\movielens\spark-movie-lens\app.py", line 5, in <module>
    from engine import RecommendationEngine
  File "F:\Data Science\movielens\spark-movie-lens\engine.py", line 115
    self.seed = 5L
                 ^
SyntaxError: invalid syntax

**Comment by burakozdemir32** [comment]
You should delete "L", it was deprecated in Python 3. "L" makes it a long integer in Python 2, but in Python 3 it's automatically done.

**Comment by jadianes** [comment]
The repo is using Python 2.

**Comment by burakozdemir32** [comment]
I think @sidmouthwebdesign tried to use Python 3.
